const tractos = "IRAPUATO TRACTOS GUZMAN";
const cajas = "GUZMAN IRAPUATO CAJAS";
const dobles_tractos = "DEV GUZMAN TRACTOS DOBLES";
const dobles_cajas = "GUZMAN CAJAS DOBLES";

export const GROUPS_FILTER = [
  "TRACTOS DASHBOARD",
  // "GUZ REFRI VARIACION",
//   "GUZMAN IRAPUATO CAJAS",
//   "DEV GUZMAN TRACTOS DOBLES",
//   "GUZMAN CAJAS DOBLES",
//   "DEV-GUZMAN-DESVIADAS",
  // "GUZMAN SECO",
  // "GUZMAN REFRIGERADO"
]